[package]
name = "gui"
version = "0.1.0"
authors = ["wk30 <foo_stacker@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
AnSiTc /Users/zzq/Projects/shitcode/rust-examples/gui
AnSiTu zzq
]2;zzq@bogon:~/Projects/shitcode/rust-examples/gui]1;..-examples/gui
rust-examples/gui on î‚  master [â‡¡?] is ğŸ“¦ v0.1.0 via ğ—¥ v1.46.0
âœ

]2;zzq@bogon:~/Projects/shitcode/rust-examples/gui]1;..-examples/gui
rust-examples/gui on î‚  master [â‡¡?] is ğŸ“¦ v0.1.0 via ğ—¥ v1.46.0
âœ clear
  clear
]2;zzq@bogon:~/Projects/shitcode/rust-examples/gui]1;..-examples/gui
rust-examples/gui on î‚  master [â‡¡?] is ğŸ“¦ v0.1.0 via ğ—¥ v1.46.0
âœ

]2;zzq@bogon:~/Projects/shitcode/rust-examples/gui]1;..-examples/gui
rust-examples/gui on î‚  master [â‡¡?] is ğŸ“¦ v0.1.0 via ğ—¥ v1.46.0
âœ cargo run
  cargo run
]2;cargo run]1;cargo   Compiling gui v0.1.0 (/Users/zzq/Projects/shitcode/rust-examples/gui)
error[E0432]: unresolved import `gui_oop`
 --> src/main.rs:1:5
  |
1 | use gui_oop::Draw;
  |     ^^^^^^^ use of undeclared type or module `gui_oop`

error[E0432]: unresolved import `gui_oop`
 --> src/main.rs:2:5
  |
2 | use gui_oop::{Button, Screen};
  |     ^^^^^^^ use of undeclared type or module `gui_oop`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `gui`.

To learn more, run the command again with --verbose.
]2;zzq@bogon:~/Projects/shitcode/rust-examples/gui]1;..-examples/gui
rust-examples/gui on î‚  master [â‡¡?] is ğŸ“¦ v0.1.0 via ğ—¥ v1.46.0
âœ 
